name: Test DB

on: push

jobs:
    bun-test-db:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Install bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
                  cache: bun

            - name: Install dependencies
              run: bun install --frozen-lockfile

            - name: Write dbs-config.yaml
              run: |
                  cat > dbs-config.yaml <<'EOF'
                  ${{ secrets.DBS_CONFIG_YAML }}
                  EOF

            - name: Set Git date
              run: echo "GIT_DATE=$(git log -1 --format=%cd --date=short)" >> $GITHUB_ENV

            - name: Run DB SQL tests
              run: bun test:sql
              env:
                  DB_TESTS: 'true'
                  GIT_DATE: ${{ env.GIT_DATE }}
                  GIT_COMMIT: ${{ github.sha }}
                  GIT_REPOSITORY: ${{ github.repository }}
